[build]
  command = "pip install -r requirements-minimal.txt"
  functions = "netlify-functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/application/*"
  to = "/application.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 